import type { ArchetypeSpec, CreatureArchetype } from './types';

/**
 * Definição dos 15 arquétipos. Cada um declara os POOLS de traços coerentes —
 * é isso que faz o sistema gerar milhões de criaturas plausíveis (nunca uma
 * cobra com asa de borboleta) e ainda assim ultrapassar 10 mil modelos com
 * folga gigante.
 */
export const ARCHETYPES: Record<CreatureArchetype, ArchetypeSpec> = {
  feline: {
    id: 'feline', label: 'Felino', baseRarity: 'comum', cheeks: true,
    bodyPlans: ['round', 'oval', 'teardrop'],
    ears: ['cat', 'fox', 'tuft'],
    eyes: ['round', 'sparkle', 'sleepy', 'sharp'],
    snouts: ['cat', 'muzzle'],
    tails: ['cat', 'foxFluffy', 'curl'],
    wings: ['none', 'energy'],
    crowns: ['none', 'antenna'],
    patterns: ['plain', 'spots', 'stripes', 'belly', 'freckles'],
    limbs: ['twoLegs', 'fourLegs'],
    sizes: ['small', 'medium'],
  },
  canine: {
    id: 'canine', label: 'Canino', baseRarity: 'comum', cheeks: true,
    bodyPlans: ['round', 'oval', 'squat'],
    ears: ['fox', 'round', 'rabbit', 'cat'],
    eyes: ['round', 'sparkle', 'big', 'droopy'],
    snouts: ['dog', 'muzzle'],
    tails: ['foxFluffy', 'curl', 'cat'],
    wings: ['none'],
    crowns: ['none', 'antenna'],
    patterns: ['plain', 'spots', 'belly', 'freckles'],
    limbs: ['fourLegs', 'twoLegs'],
    sizes: ['small', 'medium', 'large'],
  },
  avian: {
    id: 'avian', label: 'Ave', baseRarity: 'comum', cheeks: true,
    bodyPlans: ['round', 'teardrop', 'oval'],
    ears: ['none', 'tuft', 'feather'],
    eyes: ['round', 'sparkle', 'big', 'sharp'],
    snouts: ['beakShort', 'beakLong'],
    tails: ['feather', 'fish'],
    wings: ['feather', 'energy'],
    crowns: ['crest', 'none', 'antenna'],
    patterns: ['plain', 'belly', 'spots', 'freckles'],
    limbs: ['twoLegs'],
    sizes: ['small', 'medium'],
  },
  reptile: {
    id: 'reptile', label: 'Réptil', baseRarity: 'incomum', cheeks: false,
    bodyPlans: ['long', 'oval', 'squat', 'serpentine'],
    ears: ['none', 'fin'],
    eyes: ['sharp', 'round', 'sleepy'],
    snouts: ['muzzle', 'frog'],
    tails: ['lizard', 'curl'],
    wings: ['none'],
    crowns: ['none', 'crest', 'twinHorn'],
    patterns: ['scales', 'spots', 'stripes', 'plain'],
    limbs: ['fourLegs', 'none'],
    sizes: ['small', 'medium', 'large'],
  },
  draconic: {
    id: 'draconic', label: 'Dragãozinho', baseRarity: 'raro', cheeks: false,
    bodyPlans: ['oval', 'tall', 'squat'],
    ears: ['none', 'fin', 'tuft'],
    eyes: ['sharp', 'round', 'sparkle'],
    snouts: ['muzzle', 'dog'],
    tails: ['lizard', 'foxFluffy'],
    wings: ['bat', 'feather', 'energy'],
    crowns: ['twinHorn', 'singleHorn', 'crest', 'flame'],
    patterns: ['scales', 'spots', 'stripes', 'plain'],
    limbs: ['fourLegs', 'twoLegs'],
    sizes: ['medium', 'large'],
  },
  aquatic: {
    id: 'aquatic', label: 'Aquático', baseRarity: 'incomum', cheeks: true,
    bodyPlans: ['teardrop', 'oval', 'long', 'round'],
    ears: ['fin', 'none'],
    eyes: ['big', 'round', 'sparkle', 'sleepy'],
    snouts: ['none', 'beakShort'],
    tails: ['fish', 'wisp'],
    wings: ['fin', 'none'],
    crowns: ['none', 'antenna', 'crest'],
    patterns: ['belly', 'spots', 'plain', 'scales'],
    limbs: ['fins', 'none'],
    sizes: ['small', 'medium', 'large'],
  },
  amphibian: {
    id: 'amphibian', label: 'Anfíbio', baseRarity: 'incomum', cheeks: true,
    bodyPlans: ['round', 'squat', 'blob'],
    ears: ['none'],
    eyes: ['big', 'round', 'droopy'],
    snouts: ['frog', 'none'],
    tails: ['none', 'wisp'],
    wings: ['none'],
    crowns: ['none', 'antenna', 'leafSprout'],
    patterns: ['spots', 'belly', 'plain', 'swirl'],
    limbs: ['fourLegs', 'twoLegs'],
    sizes: ['small', 'medium'],
  },
  rodent: {
    id: 'rodent', label: 'Roedor', baseRarity: 'comum', cheeks: true,
    bodyPlans: ['round', 'teardrop', 'oval'],
    ears: ['round', 'rabbit', 'cat'],
    eyes: ['big', 'round', 'sparkle'],
    snouts: ['cat', 'none'],
    tails: ['curl', 'foxFluffy', 'none'],
    wings: ['none'],
    crowns: ['none', 'antenna'],
    patterns: ['plain', 'belly', 'spots', 'freckles'],
    limbs: ['twoLegs', 'fourLegs'],
    sizes: ['small'],
  },
  ursine: {
    id: 'ursine', label: 'Urso', baseRarity: 'incomum', cheeks: true,
    bodyPlans: ['round', 'squat', 'oval'],
    ears: ['round', 'cat'],
    eyes: ['round', 'sleepy', 'droopy', 'big'],
    snouts: ['dog', 'muzzle'],
    tails: ['none', 'curl'],
    wings: ['none'],
    crowns: ['none'],
    patterns: ['plain', 'belly', 'spots'],
    limbs: ['fourLegs', 'twoLegs'],
    sizes: ['medium', 'large'],
  },
  insectoid: {
    id: 'insectoid', label: 'Inseto', baseRarity: 'incomum', cheeks: false,
    bodyPlans: ['oval', 'round', 'teardrop'],
    ears: ['none'],
    eyes: ['sparkle', 'big', 'round', 'sharp'],
    snouts: ['none'],
    tails: ['wisp', 'none'],
    wings: ['butterfly', 'energy', 'feather'],
    crowns: ['antenna', 'twinHorn', 'crest'],
    patterns: ['spots', 'stripes', 'swirl', 'petals'],
    limbs: ['twoLegs', 'fourLegs', 'none'],
    sizes: ['small', 'medium'],
  },
  plant: {
    id: 'plant', label: 'Florzinha', baseRarity: 'incomum', cheeks: true,
    bodyPlans: ['round', 'teardrop', 'blob'],
    ears: ['none', 'tuft'],
    eyes: ['round', 'sparkle', 'sleepy', 'droopy'],
    snouts: ['none'],
    tails: ['leaf', 'none'],
    wings: ['none', 'butterfly'],
    crowns: ['leafSprout', 'crest', 'none'],
    patterns: ['petals', 'plain', 'spots', 'swirl'],
    limbs: ['roots', 'twoLegs', 'none'],
    sizes: ['small', 'medium'],
  },
  crystalline: {
    id: 'crystalline', label: 'Cristal', baseRarity: 'raro', cheeks: false,
    bodyPlans: ['tall', 'teardrop', 'oval'],
    ears: ['none', 'fin'],
    eyes: ['sharp', 'sparkle', 'round'],
    snouts: ['none'],
    tails: ['wisp', 'none'],
    wings: ['energy', 'none'],
    crowns: ['singleHorn', 'twinHorn', 'crest', 'halo'],
    patterns: ['scales', 'swirl', 'plain'],
    limbs: ['none', 'twoLegs'],
    sizes: ['small', 'medium', 'large'],
  },
  spirit: {
    id: 'spirit', label: 'Espírito', baseRarity: 'raro', cheeks: true,
    bodyPlans: ['teardrop', 'blob', 'round'],
    ears: ['none', 'tuft', 'cat'],
    eyes: ['round', 'sleepy', 'droopy', 'sparkle'],
    snouts: ['none'],
    tails: ['wisp', 'none'],
    wings: ['energy', 'none'],
    crowns: ['halo', 'flame', 'none', 'antenna'],
    patterns: ['swirl', 'plain', 'spots'],
    limbs: ['none'],
    sizes: ['small', 'medium'],
  },
  mythic: {
    id: 'mythic', label: 'Quimera', baseRarity: 'épico', cheeks: false,
    bodyPlans: ['oval', 'tall', 'teardrop'],
    ears: ['fox', 'tuft', 'fin'],
    eyes: ['sparkle', 'sharp', 'big'],
    snouts: ['muzzle', 'dog'],
    tails: ['foxFluffy', 'feather', 'wisp', 'lizard'],
    wings: ['feather', 'energy', 'butterfly'],
    crowns: ['singleHorn', 'twinHorn', 'halo', 'flame', 'crest'],
    patterns: ['swirl', 'scales', 'spots', 'petals'],
    limbs: ['fourLegs', 'twoLegs'],
    sizes: ['medium', 'large'],
  },
  slime: {
    id: 'slime', label: 'Gosminha', baseRarity: 'comum', cheeks: true,
    bodyPlans: ['blob', 'round', 'teardrop'],
    ears: ['none', 'tuft'],
    eyes: ['round', 'sparkle', 'big', 'sleepy'],
    snouts: ['none'],
    tails: ['none', 'wisp'],
    wings: ['none'],
    crowns: ['none', 'antenna', 'leafSprout'],
    patterns: ['plain', 'spots', 'belly', 'swirl'],
    limbs: ['none', 'twoLegs'],
    sizes: ['small', 'medium'],
  },
};

export const ARCHETYPE_IDS = Object.keys(ARCHETYPES) as CreatureArchetype[];
